[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories
    | \.direnv
    | \.venv
    | venv
  )/
)
'''

[tool.coverage.run]
branch = true
omit = []

[tool.coverage.report]
# fail_under = 100
skip_covered = true
exclude_lines = [
    # this is the default, but has to be included explicitly now we specify exclude_lines
    "pragma: no cover",
    # this indicates that the line should never be hit
    "assert False",
    # this condition is only true when a module is run as a script
    'if __name__ == "__main__":',
    # this indicates that a method should be defined in a subclass
    "raise NotImplementedError",
]

[tool.coverage.html]

[tool.interrogate]
fail-under = 0
ignore-init-module = true
omit-covered-files = true
verbose = 1

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
lines_after_imports = 2
multi_line_output = 3
skip_glob = [".direnv", "venv", ".venv"]
use_parentheses = true

[tool.mypy]
files = "cohortextractor"
plugins = [
  "sqlmypy",
]

# Consider turning on these stricter options later.  They require a
# significantly larger number of changes to the codebase so we have decided to
# work towards them.
# check_untyped_defs = true
# disallow_untyped_calls = true
# disallow_untyped_decorators = true
# disallow_untyped_defs = true

# https://mypy.readthedocs.io/en/stable/config_file.html#confval-disallow_incomplete_defs
disallow_incomplete_defs = true

# https://mypy.readthedocs.io/en/stable/config_file.html#confval-no_implicit_optional
no_implicit_optional = true

# https://mypy.readthedocs.io/en/stable/config_file.html#confval-warn_redundant_casts
warn_redundant_casts = true

# https://mypy.readthedocs.io/en/stable/config_file.html#confval-warn_unused_ignores
warn_unused_ignores = true

# https://mypy.readthedocs.io/en/stable/config_file.html#confval-warn_unreachable
warn_unreachable = true

# https://mypy.readthedocs.io/en/stable/config_file.html#confval-scripts_are_modules
scripts_are_modules = true

# https://mypy.readthedocs.io/en/stable/config_file.html#confval-show_error_codes
show_error_codes = true

[[tool.mypy.overrides]]
module = "pyhive.sqlalchemy_hive.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--tb=native --strict-markers"
markers = [
    "integration: tests that use a database",
    "smoke: tests that run the cohort extractor in its container against a database",
]
filterwarnings = [
    "ignore::DeprecationWarning:past.builtins.misc:45"
]
