name: Build and publish image

on:
  create:
  workflow_dispatch:

jobs:
  build-and-publish-docker-image:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    env:
      image: ghcr.io/opensafely-core/databuilder
      ce_image: ghcr.io/opensafely-core/cohortextractor-v2
    steps:
      - uses: actions/checkout@v2

      - name: Get current git tag
        id: tags
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.image }}:latest --tag ${{ env.ce_image }}:latest

      - name: Log into GitHub Container Registry
        run: docker login https://ghcr.io -u ${{ github.actor }} --password ${{ secrets.DOCKER_RW_TOKEN }}

      - name: Push images to GitHub Container Registry
        env:
          VERSION: ${{ steps.tags.outputs.tag }}
        run: |
          docker tag ${{ env.image }} ${{ env.image }}:$VERSION
          docker tag ${{ env.ce_image }} ${{ env.ce_image }}:$VERSION
          docker push ${{ env.image }}:$VERSION
          docker push ${{ env.ce_image }}:$VERSION
