name: Build and publish image

on:
  create:
  workflow_dispatch:

jobs:
  build-and-publish-docker-image:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    env:
      image: ghcr.io/opensafely-core/databuilder
      ce_image: ghcr.io/opensafely-core/cohortextractor-v2
    steps:
      - uses: actions/checkout@v2

      # This relies on the tag having a version of the form vX.Y.Z
      - name: Build image
        run: |
          PATCH="${GITHUB_REF#refs/*/}"
          MAJOR="${PATCH%%.*}"
          MINOR="${PATCH%.*}"
          docker build . --file Dockerfile \
            --tag ${{ env.image }}:$MAJOR --tag ${{ env.ce_image }}:$MAJOR \
            --tag ${{ env.image }}:$MINOR --tag ${{ env.ce_image }}:$MINOR \
            --tag ${{ env.image }}:$PATCH --tag ${{ env.ce_image }}:$PATCH

      - name: Log into GitHub Container Registry
        run: docker login https://ghcr.io -u ${{ github.actor }} --password ${{ secrets.DOCKER_RW_TOKEN }}

      - name: Push images to GitHub Container Registry
        run: |
          docker push --all-tags ${{ env.image }}
          docker push --all-tags ${{ env.ce_image }}
